/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package iu;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.JLabel;
import javax.swing.Timer;
import modelo.Xogo;

/**
 *
 * @author a14carlosfd
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    private int time = 0;
    private int score = 0;
    private int speed = 900;
    private Xogo xogo;

    Timer timerCrono;
    Timer timer;
    // Timer timer;
    private boolean pause = false;

    public VentanaPrincipal() {

        initComponents();
        startCrono();
        startSpeed();

        xogo = new Xogo(this);
        xogo.xenerarNovaFicha();
        panelXogo.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        panelXogo = new javax.swing.JPanel();
        lblBackgroundGame = new javax.swing.JLabel();
        panelScore = new javax.swing.JPanel();
        lblScoreTitle = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        panelNextFigure = new javax.swing.JPanel();
        lblNextTitle = new javax.swing.JLabel();
        panelLevel = new javax.swing.JPanel();
        lblLevelTitle = new javax.swing.JLabel();
        lbllinesNextLevelTitle = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        lblMenuTitle = new javax.swing.JLabel();
        tglPause = new javax.swing.JToggleButton();
        btnExit = new javax.swing.JButton();
        btnRestart = new javax.swing.JButton();
        panelLine = new javax.swing.JPanel();
        lblLine = new javax.swing.JLabel();
        panelTime = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        lblTimeTitle = new javax.swing.JLabel();
        backgroundProgram = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1100, 950));
        setMinimumSize(new java.awt.Dimension(1100, 950));
        setUndecorated(true);
        setPreferredSize(null);
        setResizable(false);
        setSize(new java.awt.Dimension(1100, 950));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(102, 102, 102));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelXogo.setBackground(new java.awt.Color(204, 204, 255));
        panelXogo.setMaximumSize(new java.awt.Dimension(500, 900));
        panelXogo.setMinimumSize(new java.awt.Dimension(500, 900));
        panelXogo.setName(""); // NOI18N
        panelXogo.setOpaque(false);
        panelXogo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                panelXogoKeyTyped(evt);
            }
        });
        panelXogo.setLayout(null);
        mainPanel.add(panelXogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 500, 900));

        lblBackgroundGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundsGame/10x18backgroundGameSafeZone.png"))); // NOI18N
        lblBackgroundGame.setText("lblBackgroundGame");
        lblBackgroundGame.setMaximumSize(new java.awt.Dimension(500, 900));
        lblBackgroundGame.setMinimumSize(new java.awt.Dimension(500, 900));
        lblBackgroundGame.setPreferredSize(new java.awt.Dimension(500, 900));
        mainPanel.add(lblBackgroundGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 500, 900));
        lblBackgroundGame.getAccessibleContext().setAccessibleParent(mainPanel);

        panelScore.setMinimumSize(new java.awt.Dimension(53, 53));
        panelScore.setPreferredSize(new java.awt.Dimension(110, 110));
        panelScore.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblScoreTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblScoreTitle.setText("Score");
        panelScore.add(lblScoreTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 5, -1, -1));

        lblScore.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScore.setText("0");
        panelScore.add(lblScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 70, 180, -1));

        mainPanel.add(panelScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 220, 130));

        panelNextFigure.setMaximumSize(new java.awt.Dimension(220, 260));
        panelNextFigure.setMinimumSize(new java.awt.Dimension(220, 260));
        panelNextFigure.setPreferredSize(new java.awt.Dimension(220, 260));

        lblNextTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblNextTitle.setText("Next");
        panelNextFigure.add(lblNextTitle);

        mainPanel.add(panelNextFigure, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 220, 280));

        panelLevel.setPreferredSize(new java.awt.Dimension(220, 220));
        panelLevel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLevelTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblLevelTitle.setText("Level");
        panelLevel.add(lblLevelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        lbllinesNextLevelTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbllinesNextLevelTitle.setText("Lines for next level:");
        panelLevel.add(lbllinesNextLevelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        mainPanel.add(panelLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, 220, 240));

        panelMenu.setMaximumSize(new java.awt.Dimension(220, 260));
        panelMenu.setMinimumSize(new java.awt.Dimension(220, 260));
        panelMenu.setPreferredSize(new java.awt.Dimension(220, 260));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblMenuTitle.setText("Menu");
        panelMenu.add(lblMenuTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 20, 91, 41));

        tglPause.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tglPause.setText("Pause");
        tglPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglPauseActionPerformed(evt);
            }
        });
        panelMenu.add(tglPause, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 90, 150, 40));

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        panelMenu.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 190, 150, 40));

        btnRestart.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRestart.setText("Restart");
        panelMenu.add(btnRestart, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 140, 150, 40));

        mainPanel.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 690, 220, 240));

        lblLine.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblLine.setText("Lines");
        panelLine.add(lblLine);

        mainPanel.add(panelLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 220, 130));

        panelTime.setMaximumSize(new java.awt.Dimension(220, 130));
        panelTime.setMinimumSize(new java.awt.Dimension(220, 130));
        panelTime.setPreferredSize(new java.awt.Dimension(220, 130));
        panelTime.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTime.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime.setText("0");
        panelTime.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, -1));

        lblTimeTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTimeTitle.setText("Time");
        panelTime.add(lblTimeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 5, -1, -1));

        mainPanel.add(panelTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 380, 220, 130));

        backgroundProgram.setText("backgroundProgram");
        mainPanel.add(backgroundProgram, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 950));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 950));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tglPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglPauseActionPerformed
        if (!pause) {
            pauseCronos();
        } else
            resumeCronos();
    }//GEN-LAST:event_tglPauseActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void panelXogoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelXogoKeyTyped

        if (evt.getKeyChar() == KeyEvent.VK_DOWN) {
            System.out.println("Inserta texto");
        }

        switch (evt.getKeyChar()) {

            case 's' -> {
                xogo.moverFichaAbaixo();
                mainPanel.updateUI();
                //reiniciamos timer para que la ficha no baje 2 posiciones seguidas.
                timer.restart();
            }
            case 'd' ->
                xogo.moverDereita();
            case 'a' ->
                xogo.moverEsquerda();
            case 'w' ->
                xogo.rotarFicha();
            default -> {
            }
        }


    }//GEN-LAST:event_panelXogoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundProgram;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRestart;
    private javax.swing.JLabel lblBackgroundGame;
    private javax.swing.JLabel lblLevelTitle;
    private javax.swing.JLabel lblLine;
    private javax.swing.JLabel lblMenuTitle;
    private javax.swing.JLabel lblNextTitle;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblScoreTitle;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTimeTitle;
    private javax.swing.JLabel lbllinesNextLevelTitle;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelLevel;
    private javax.swing.JPanel panelLine;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelNextFigure;
    private javax.swing.JPanel panelScore;
    private javax.swing.JPanel panelTime;
    private javax.swing.JPanel panelXogo;
    private javax.swing.JToggleButton tglPause;
    // End of variables declaration//GEN-END:variables

    public void pintarCadrado(JLabel lblCadrado) {
        panelXogo.add(lblCadrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(lblCadrado.getX(), lblCadrado.getY(), 50, 50));
    }

    public void borrarCadrado(JLabel lblCadrado) {
        panelXogo.remove(lblCadrado);
    }

    public void mostrarNumeroLinas() {
        lblLine.setText(String.valueOf(xogo.getNumerolineas()));
    }

    public void mostrarFinDoXogo() {
        //pausas de los cronos
        //mostrar popup con puntuacion y boton de reinicio.
        //destruir el juego 
        //reiniciar cronos
    }

//    private void iniciarPartida() {
//    }

    private void pauseCronos() {

        timerCrono.stop();
        timer.stop();
        pause = true;
    }

    private void resumeCronos() {

        timerCrono.start();
        timer.start();
        pause = false;
    }

    private void startCrono() {

        timerCrono = new Timer(1000, (ActionEvent e) -> {
            if (time < 10) {
                lblTime.setText(String.valueOf("0" + time));
            } else {
                lblTime.setText(String.valueOf(time));
            }
            time++;

        });
        timerCrono.start();
    }

    private void startSpeed() {

        timer = new Timer(speed, (ActionEvent e) -> {
            score++;
            lblScore.setText(String.valueOf(score));
            xogo.moverFichaAbaixo();
            mainPanel.updateUI();
        });
        timer.start();
    }

}
